version: '3.4'

services:
  api_techchallengefiap:
    image: rianholanda91/apitechchallengefiap
    build:
      context: .
      dockerfile: API_TechChallengeFiap/Dockerfile
    ports:    
      - '8080:8080'    
      - '8081:8081'
    networks:   
      - mynetwork
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1q2w3e4r@#"
    ports:
      - "1433:1433"
    networks:   
      - mynetwork
networks:  
  mynetwork:
