apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: api-techchallengefiap  
spec:  
  replicas: 2  
  selector:  
    matchLabels:  
      app: api-techchallengefiap  
  template:  
    metadata:  
      labels:  
        app: api-techchallengefiap  
    spec:  
      containers:  
      - name: api-techchallengefiap  
        image: rianholanda91/apitechchallengefiap:latest  
        ports:  
        - containerPort: 8080  
        - containerPort: 8081  
---  
apiVersion: v1  
kind: Service  
metadata:  
  name: api-techchallengefiap  
spec:  
  type: NodePort  
  ports:  
  - name: port1  
    port: 8080  
    targetPort: 8080  
  - name: port2  
    port: 8081  
    targetPort: 8081  
  selector:  
    app: api-techchallengefiap  